//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWiki.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedIp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlockedIp()
        {
            this.BlockedIps1 = new HashSet<BlockedIp>();
        }
    
        public int Id { get; set; }
        public bool AnonymousOnly { get; set; }
        public string BlockByUserId { get; set; }
        public bool BlockCreateAccount { get; set; }
        public decimal BlockExpiry { get; set; }
        public string BlockReason { get; set; }
        public bool BlockUserEdit { get; set; }
        public Nullable<int> BlockedIpId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public string IpAddress { get; set; }
        public string IpRangeEnd { get; set; }
        public string IpRangeStart { get; set; }
        public Nullable<int> ParentBlock { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserId { get; set; }
        public string UserBlockedId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockedIp> BlockedIps1 { get; set; }
        public virtual BlockedIp BlockedIp1 { get; set; }
    }
}
