//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWiki.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterSection
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public int CharacterSectionGroupId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public string Slug { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserId { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual CharacterSectionGroup CharacterSectionGroup { get; set; }
    }
}
