//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWiki.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileArchive
    {
        public int Id { get; set; }
        public string ArchiveName { get; set; }
        public int BitDepth { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public string DeletedReason { get; set; }
        public string FileDescription { get; set; }
        public string FileMediaType { get; set; }
        public string FileMime { get; set; }
        public int FileSize { get; set; }
        public string FileSource { get; set; }
        public int Height { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserId { get; set; }
        public string UploadedUserId { get; set; }
        public int Width { get; set; }
    }
}
