//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWiki.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public Nullable<int> CharacterId { get; set; }
        public Nullable<int> CharacterId1 { get; set; }
        public float Cooldown { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public float CritChange { get; set; }
        public float DPS { get; set; }
        public int Energy { get; set; }
        public string Name { get; set; }
        public float Power { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserId { get; set; }
        public float WithSTAB { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Character Character1 { get; set; }
    }
}
