//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWiki.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecentChanx
    {
        public int Id { get; set; }
        public string ChangeComment { get; set; }
        public string ChangeFromIpAddress { get; set; }
        public Nullable<decimal> ChangeNewLength { get; set; }
        public Nullable<decimal> ChangeOldLength { get; set; }
        public int ChangeType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public bool IsCreateNew { get; set; }
        public bool IsDeletedAction { get; set; }
        public int NameSpace { get; set; }
        public Nullable<int> PageId { get; set; }
        public string PageTitle { get; set; }
        public Nullable<int> RevisionId { get; set; }
        public Nullable<int> RevisionParentId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserId { get; set; }
        public int UserId { get; set; }
        public string UserMakeChangeId { get; set; }
    }
}
