//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWiki.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public string SiteConfig { get; set; }
        public string SiteDomain { get; set; }
        public string SiteGroup { get; set; }
        public string SiteKey { get; set; }
        public string SiteLanguage { get; set; }
        public string SiteProtocol { get; set; }
        public string SiteSource { get; set; }
        public string SiteType { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserId { get; set; }
    }
}
