//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWiki.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WikiImage
    {
        public int Id { get; set; }
        public int BitDepth { get; set; }
        public Nullable<int> CharacterId { get; set; }
        public Nullable<int> CharacterId1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public string ImageDescription { get; set; }
        public int ImageHeight { get; set; }
        public string ImageMediaType { get; set; }
        public string ImageMime { get; set; }
        public string ImageName { get; set; }
        public int ImageSize { get; set; }
        public int ImageWidth { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserId { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Character Character1 { get; set; }
    }
}
